id: I3DE5441E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T16:32:52+00:00'
last_modified: '2022-06-07T17:07:31.728320+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7776
  title: གླིང་རྗེ་གེ་སར་སྐྱེས་བུའི་མཆོད་སྒྲུབ་ཕྱོགས་བསྡུས་བྱིན་རླབས་གཏེར་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    9CEB:
      image_group_id: I3CN7778
      title: ''
      total_pages: 600
      order: 1
      base_file: 9CEB.txt
    E190:
      image_group_id: I3CN7779
      title: ''
      total_pages: 608
      order: 2
      base_file: E190.txt
    86E0:
      image_group_id: I3CN7780
      title: ''
      total_pages: 540
      order: 3
      base_file: 86E0.txt
    A816:
      image_group_id: I3CN7781
      title: ''
      total_pages: 520
      order: 4
      base_file: A816.txt
    24B2:
      image_group_id: I3CN7782
      title: ''
      total_pages: 488
      order: 5
      base_file: 24B2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
