id: P003036
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7776
  title: གླིང་རྗེ་གེ་སར་སྐྱེས་བུའི་མཆོད་སྒྲུབ་ཕྱོགས་བསྡུས་བྱིན་རླབས་གཏེར་མཛོད།
  author: ''
  volumes:
    4a2a70e6da03435f9e50c1629bc605d1:
      image_group_id: I3CN7778
      title: ''
      volume_number: 1
      total_pages: 600
    6e4735a2159a4736bb0fafb1d107b00e:
      image_group_id: I3CN7779
      title: ''
      volume_number: 2
      total_pages: 608
    29eaa52f2f7d4f4cb9047b82d61baa1d:
      image_group_id: I3CN7780
      title: ''
      volume_number: 3
      total_pages: 540
    a273b4e1c4d44e52a6302ecb43b13e4b:
      image_group_id: I3CN7781
      title: ''
      volume_number: 4
      total_pages: 520
    dcf522d6661541ceb7185f478e98b9d1:
      image_group_id: I3CN7782
      title: ''
      volume_number: 5
      total_pages: 488
    42875dcec3c84ce59c4079378431986b:
      image_group_id: I3CN7783
      title: ''
      volume_number: 6
      total_pages: 616
      base_file: v001.txt
    c6948edc1c0a4ae39d57feb6314e53f5:
      image_group_id: I3CN7784
      title: ''
      volume_number: 7
      total_pages: 571
      base_file: v002.txt
    d59a3789aa134312aa7b09c7624e2486:
      image_group_id: I3CN7785
      title: ''
      volume_number: 8
      total_pages: 648
      base_file: v003.txt
    8cb1bc4a72c7472493a02365be325c5f:
      image_group_id: I3CN7786
      title: ''
      volume_number: 9
      total_pages: 532
      base_file: v004.txt
    4bc9bd85ee6a45a98ae4ba8ac9c34a61:
      image_group_id: I3CN7787
      title: ''
      volume_number: 10
      total_pages: 300
      base_file: v005.txt
